const coefficients = {
  "high school": {
    "1AS": {
      "common core science": {
        arabic: 3,
        english: 2,
        french: 2,
        islamic: 2,
        historyGio: 2,
        math: 5,
        physics: 4,
        science: 4,
        techno: 2,
        informatic: 2,
        sport: 1,
        art: 1,
        amzigh: 2,
      },
      "common core literature": {
        arabic: 5,
        english: 3,
        french: 3,
        islamic: 2,
        historyGio: 3,
        math: 2,
        physics: 2,
        science: 2,
        informatic: 2,
        sport: 1,
        art: 1,
        amzigh: 2,
      },
    },
    "2AS": {
      
            
      "philosophy": {
        arabic: 5,
        philo: 4,
        historyGio: 3,
        amzigh: 3,
        english: 2,
        french: 2,
        informatic: 2,
        math: 2,
        science: 2,
        islamic: 2,
        sport: 1,
        art: 1,
      },
      "languages": {
        SpGerIt: 5,
        english: 4,
        french: 3,
        arabic: 3,
        amzigh: 2,
        philo: 2,
        historyGio: 2,
        informatic: 2,
        math: 2,
        islamic: 2,
        sport: 1,
        art: 1,
      },
      "art": {
        art1: 5,
        art2: 4,
        arabic: 3,
        amzigh: 3,
        english: 2,
        french: 2,
        philo: 2,
        historyGio: 2,
        informatic: 2,
        math: 2,
        physics: 1,
        islamic: 1,
        sport: 1,
      },
      "math": {
        math: 6,
        physics: 4,
        arabic: 2,
        amzigh: 2,
        informatic: 2,
        science: 2,
        english: 2,
        philo: 2,
        historyGio: 2,
        islamic: 2,
        french: 2,
        sport: 1,
        art: 1,
      },
      "economics": {
        accounting: 5,
        economic: 3,
        math: 4,
        arabic: 2,
        amzigh: 2,
        informatic: 2,
        english: 3,
        philo: 2,
        law: 2,
        historyGio: 2,
        islamic: 2,
        french: 2,
        sport: 1,
        art: 1,
      },
      "science": {
        science: 5,
        physics: 4,
        math: 4,
        arabic: 2,
        amzigh: 2,
        informatic: 2,
        english: 3,
        philo: 2,
        historyGio: 2,
        islamic: 2,
        french: 2,
        sport: 1,
        art: 1,
      },
      "technique math": {
        techo: 6,
        math: 4,
        physics: 3,
        arabic: 2,
        amzigh: 2,
        informatic: 2,
        english: 3,
        philo: 2,
        historyGio: 2,
        islamic: 2,
        french: 2,
        sport: 1,
        art: 1,
      },
    },
    "3AS": {
      "philosophy": {
        arabic: 7,
        philo: 6,
        historyGio: 4,
        amzigh: 3,
        english: 3,
        french: 2,
        islamic: 2,
        sport: 1,
      },
      "languages": {
        SpGerIt: 6,
        english: 4,
        french: 4,
        arabic: 2,
        amzigh: 2,
        historyGio: 2,
        islamic: 2,
        sport: 1,
      },
      "art": {
        art1: 6,
        art2: 5,
        arabic: 4,
        amzigh: 3,
        english: 2,
        french: 2,
        historyGio: 2,
        islamic: 2,
        sport: 1,
      },
      "math": {
        math: 8,
        physics: 6,
        informatic: 3,
        science: 2,
        english: 3,
        historyGio: 2,
        islamic: 2,
        sport: 1,
      },
      "economics": {
        accounting: 6,
        economic: 4,
        math: 3,
        arabic: 2,
        amzigh: 2,
        english: 3,
        low: 2,
        historyGio: 3,
        islamic: 2,
        sport: 1,
      },
      "science": {
        science: 6,
        physics: 5,
        math: 4,
        arabic: 2,
        amzigh: 2,
        english: 3,
        historyGio: 2,
        islamic: 2,
        sport: 1,
      },
      "technique math": {
        techo: 6,
        math: 5,
        physics: 4,
        arabic: 2,
        amzigh: 2,
        english: 3,
        historyGio: 2,
        islamic: 2,
        sport: 1,
      },
    },
  },
  "middle school": {
    "1AM": {
      arabic: 2,
      amzigh: 2,
      french: 1,
      english: 1,
      math: 2,
      science: 1,
      physics: 1,
      islamic: 1,
      historyGio: 2,
      civics: 1,
      art: 1,
      sport: 1,
      informatic: 1,
    },
    "2AM": {
      arabic: 3,
      amzigh: 2,
      french: 2,
      english: 1,
      math: 3,
      science: 2,
      physics: 2,
      islamic: 1,
      historyGio: 2,
      civics: 1,
      art: 1,
      sport: 1,
      informatic: 1,
    },
    "3AM": {
      arabic: 3,
      amzigh: 2,
      french: 2,
      english: 1,
      math: 3,
      science: 2,
      physics: 2,
      islamic: 1,
      historyGio: 2,
      civics: 1,
      art: 1,
      sport: 1,
      informatic: 1,
    },
    "4AM": {
      arabic: 5,
      amzigh: 2,
      french: 3,
      english: 2,
      math: 4,
      science: 2,
      physics: 2,
      islamic: 2,
      historyGio: 3,
      civics: 1,
      art: 1,
      sport: 1,
      informatic: 1,
    },
  },
};

module.exports=coefficients
